language : node_js
node_js :
 - 14
install:
 - npm install

# https://docs.travis-ci.com/user/conditions-v1
jobs:
  exclude:
    - if: branch = dev \
      commit_message !~ /(no-deploy)/
script:
 - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master