language : node_js
node_js :
 - 14
install:
 - npm install
script:
 - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master