language : node_js
node_js :
 - 14
install:
 - npm install

# https://docs.travis-ci.com/user/conditions-v1
jobs:
  exclude:
    - if: branch = dev OR commit_message =~ /(no-ci)/

script:
 - npm run test

after_script:
  # - git config user.name "user.name"
  # - git config user.email "user.email"
  - tar -zcvf /tmp/html.tar.gz . --exclude="node_modules"
  - mkdir -p ~/$TRAVIS_REPO_SLUG
  - cd ~/$TRAVIS_REPO_SLUG
  - tar -xvf /tmp/html.tar.gz -C ./
  - chmod 777 ./
  
  # - git clone --branch $TRAVIS_BRANCH https://ma125120:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git demo
  - git remote set-url origin https://ma125120:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git remote -v
  - touch test.txt
  - echo "dsa$TRAVIS_BRANCH" >> test.txt
  - ls -al
  - git add .
  - git commit -m "测试 ci"
  - echo "git push https://ma125120:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git $TRAVIS_BRANCH"
  - git push origin $TRAVIS_BRANCH

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master